info:
  name: Single Role
  type: http
  seq: 2

http:
  method: GET
  url: "{{LOCAL_ADMIN_URL}}roles/read/3"
  headers:
    - name: Authorization
      value: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6IkFkbWluIiwiaWF0IjoxNzYyMzIyOTQzLCJleHAiOjE3NjI0MDkzNDN9.XUtTCyXi1lUsJY75IIRBD_WYe5BarTma3ZSB8g_3hP0
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
