info:
  name: Create Inventory
  type: http
  seq: 3

http:
  method: POST
  url: "{{LOCAL_ADMIN_URL}}inventory/create"
  headers:
    - name: Authorization
      value: "{{TOKEN}}"
  body:
    type: json
    data: "{\r

      \    \"productVariantId\": 1,\r

      \    \"warehouseId\": 1,\r

      \    \"quantity\": 1,\r

      \    \"type\": \"DAMAGE\"\r

      }"
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
