info:
  name: Update Inventory
  type: http
  seq: 4

http:
  method: PATCH
  url: "{{LOCAL_ADMIN_URL}}inventory/update"
  headers:
    - name: Authorization
      value: "{{TOKEN}}"
  body:
    type: json
    data: |-
      {
          "productVariantId": 1,
          "warehouseId": 1,
          "quantity": 160,
          "type": "DAMAGE"
      }
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
